export const quests = [
	{
		id: 1,
		name: "Experienced Craftsman",
		description: "Craft characters at least five times using at least three different recipes",
		recurrence: 'daily',
		tokensReward: 75,
	},
	{
		id: 2,
		name: "Diverse Name",
		description: "Have your currently published name contain at least 1 letter, 1 symbol, and 1 number",
		recurrence: 'daily',
		tokensReward: 350,
	},
	{
		id: 3,
		name: "Trade Diplomat",
		description: "Successfully have your trade accepted by a player",
		recurrence: 'daily',
		tokensReward: 100,
		charactersReward: "trade",
	},
	{
		id: 4,
		name: "Twinsies",
		description: "Coordinate with another player to have the same published name as them",
		recurrence: 'daily',
		tokensReward: 200,
		charactersReward: "x",
	},
	{
		id: 5,
		name: "Get Rich Quick",
		description: "Gain 200 tokens total through any means necessary",
		recurrence: 'daily',
		tokensReward: 350,
		charactersReward: "tokens",
	},
	{
		id: 6,
		name: "Echoed Name",
		description: "Change your current name into a repeated version of itself. For example, from \"Pom\" to \"PomPom\"",
		recurrence: 'daily',
		tokensReward: 100,
		charactersReward: "echo",
	},
	{
		id: 7,
		name: "Identity Theft",
		description: "Change your current name to exactly match another player’s current name. Keep it that way for two hours straight",
		recurrence: 'daily',
		tokensReward: 350,
	},
	{
		id: 8,
		name: "Fragile Name",
		description: "Make sure your current name does not change for 8 hours straight",
		recurrence: 'daily',
		tokensReward: 500,
	},
	{
		id: 9,
		name: "Hour of Silence",
		description: "Ensure that no player changes their name for an hour straight",
		recurrence: 'daily',
		tokensReward: 250,
		charactersReward: "shhh",
	},
	{
		id: 10,
		name: "Even Number Name",
		description: "Publish a name that uses one of the following characters: 02468",
		recurrence: 'daily',
		tokensReward: 246,
		charactersReward: "13579",
	},
	{
		id: 11,
		name: "Distinct Dozen",
		description: "Publish a name that contains 12 unique characters",
		recurrence: 'daily',
		tokensReward: 120,
		charactersReward: "twelve",
	},
	{
		id: 12,
		name: "High Yield",
		description: "Earn at least five tokens from a single mine",
		recurrence: 'daily',
		tokensReward: 75,
		charactersReward: "gold",
	},
	{
		id: 13,
		name: "One Hundred Swings",
		description: "Mine 100 times",
		recurrence: 'daily',
		tokensReward: 150,
		charactersReward: "mmm",
	},
	{
		id: 14,
		name: "Rapid Extraction",
		description: "Mine at least 20 times in the span of a minute",
		recurrence: 'daily',
		tokensReward: 220,
	},
	{
		id: 15,
		name: "Miner's Fortune",
		description: "Earn at least 100 tokens just from mining",
		recurrence: 'daily',
		tokensReward: 100,
		charactersReward: "ore",
	},
	{
		id: 16,
		name: "Lucky Mining Streak",
		description: "Earn at least three tokens from a single mine five times",
		recurrence: 'daily',
		tokensReward: 125,
		charactersReward: "nnn",
	},
	{
		id: 17,
		name: "Refill Jackpot",
		description: "Earn at least 100 tokens from a single refill",
		recurrence: 'daily',
		tokensReward: 100,
		charactersReward: "refill",
	},
	{
		id: 18,
		name: "Mine Together",
		description: "Mine at the same time as two other players in the span of one minute",
		recurrence: 'daily',
		tokensReward: 250,
		charactersReward: "friend",
	},
	{
		id: 19,
		name: "Mining Speedrun",
		description: "Earn at least 35 total tokens from mines in the span of 1 minute",
		recurrence: 'daily',
		tokensReward: 125,
		charactersReward: "cash",
	},
	{
		id: 20,
		name: "Collective Mining",
		description: "Contribute to a total of 1,000 tokens mined collectively by all players",
		recurrence: 'daily',
		tokensReward: 150,
		charactersReward: "team",
	},
	{
		id: 21,
		name: "Refill Frenzy",
		description: "Claim five refills",
		recurrence: 'daily',
		tokensReward: 150,
	},
	{
		id: 22,
		name: "Instant Refill",
		description: "Claim a refill immediately after it's cooldown expires",
		recurrence: 'daily',
		tokensReward: 150,
		charactersReward: "fast",
	},
	{
		id: 23,
		name: "Refill Together",
		description: "Claim a refill at the same time as two other players in the span of one minute",
		recurrence: 'daily',
		tokensReward: 200,
		charactersReward: "trio",
	},
	{
		id: 24,
		name: "Treasure Hunter",
		description: "Open five mystery boxes",
		recurrence: 'daily',
		tokensReward: 125,
		charactersReward: "box",
	},
	{
		id: 25,
		name: "Rapid Boxes",
		description: "Open three mystery boxes in the span of one minute",
		recurrence: 'daily',
		tokensReward: 150,
		charactersReward: "speed",
	},
	{
		id: 26,
		name: "Familiar Face",
		description: "Obtain a character from a mystery box that is already in your current name",
		recurrence: 'daily',
		tokensReward: 175,
		charactersReward: "deja",
	},
	{
		id: 27,
		name: "Mystery Box Splurge",
		description: "Spend a total of 750 tokens on mystery boxes",
		recurrence: 'daily',
		tokensReward: 250,
		charactersReward: "spender",
	},
	{
		id: 28,
		name: "Mystery Box Collector",
		description: "Buy at least three different mystery boxes",
		recurrence: 'daily',
		tokensReward: 100,
		charactersReward: "a1!",
	},
	{
		id: 29,
		name: "Big Spender",
		description: "Open the most expensive mystery box",
		recurrence: 'daily',
		tokensReward: 300,
		charactersReward: "rich",
	},
	{
		id: 30,
		name: "Bonus Loot",
		description: "Receive more than one character from a single mystery box",
		recurrence: 'daily',
		tokensReward: 222,
		charactersReward: "two",
	},
	{
		id: 31,
		name: "Expected Reward",
		description: "Receive the letter \"e\" from a mystery box",
		recurrence: 'daily',
		tokensReward: 80,
		charactersReward: "aiou",
	},
	{
		id: 32,
		name: "Three of a Kind",
		description: "Receive the same character from a mystery box three times",
		recurrence: 'daily',
		tokensReward: 123,
		charactersReward: "three",
	},
	{
		id: 33,
		name: "ALL IN",
		description: "Spend all the tokens you have on a mystery box",
		recurrence: 'daily',
		charactersReward: "I'm broke",
	},
	{
		id: 34,
		name: "Emoji Alchemist",
		description: "Use any recipe to craft at an emoji",
		recurrence: 'daily',
		tokensReward: 200,
		charactersReward: "😯",
	},
	{
		id: 35,
		name: "Many for One",
		description: "Craft a character using a recipe that requires at least three characters but produces only one character in return",
		recurrence: 'daily',
		tokensReward: 50,
		charactersReward: "↻⇋⤻↹⚭✂⤡⇔",
	},
	{
		id: 36,
		name: "Great Deal",
		description: "Successfully trade a single character you own for at least three in return",
		recurrence: 'daily',
		tokensReward: 300,
		charactersReward: "deal",
	},
	{
		id: 37,
		name: "Crafty Crafter",
		description: "Craft three recipes that require a utility character",
		recurrence: 'daily',
		tokensReward: 200,
		charactersReward: "⇋Flip",
	},
	{
		id: 38,
		name: "Large Output",
		description: "Use a crafting recipe that produces at least two characters",
		recurrence: 'daily',
		tokensReward: 250,
		charactersReward: "✂Split",
	},
	{
		id: 39,
		name: "Dual Artisan",
		description: "Craft the same character using two different recipes",
		recurrence: 'daily',
		tokensReward: 225,
		charactersReward: "⚭Fuse",
	},
	{
		id: 40,
		name: "Recipe Remix",
		description: "Use the same input characters in two different recipes to produce different outputs",
		recurrence: 'daily',
		tokensReward: 300,
		charactersReward: "⇔Stretch",
	},
	{
		id: 41,
		name: "Scam",
		description: "Successfully trade only one of your characters to receive at least five characters in return",
		recurrence: 'daily',
		tokensReward: 300,
		charactersReward: "!@#$",
	},
	{
		id: 42,
		name: "Seal The Deal",
		description: "Accept a trade request",
		recurrence: 'daily',
		tokensReward: 100,
		charactersReward: "ok",
	},
	{
		id: 43,
		name: "Rejecting Profit",
		description: "Decline a trade request where you would have received at least 5 more characters than you were giving",
		recurrence: 'daily',
		tokensReward: 150,
		charactersReward: "compensation",
	},
	{
		id: 44,
		name: "Final Offer",
		description: "Have a trade request that you modified be accepted by the other player",
		recurrence: 'daily',
		tokensReward: 250,
		charactersReward: "modify",
	},
	{
		id: 45,
		name: "Quest Combo",
		description: "Complete two separate quests consecutively in the span of ten minutes",
		recurrence: 'daily',
		tokensReward: 150,
		charactersReward: "quick",
	},
	{
		id: 46,
		name: "Hoard Tokens",
		description: "Accumulate a total of 200 tokens without spending any",
		recurrence: 'daily',
		tokensReward: 200,
	},
	{
		id: 47,
		name: "The Richest",
		description: "Have the most tokens out of all players",
		recurrence: 'daily',
		tokensReward: 250,
		charactersReward: "🪙w3alτhy",
	},
	{
		id: 48,
		name: "Character Collector",
		description: "Have 35 unique characters in your inventory",
		recurrence: 'daily',
		tokensReward: 350,
		charactersReward: "=-+-=",
	},
	{
		id: 49,
		name: "You Snooze You Lose",
		description: "Be the first player to complete this quest",
		recurrence: 'daily',
		tokensReward: 400,
		charactersReward: "The Fastest",
	},
	{
		id: 50,
		name: "You Snooze You Win",
		description: "Be the second player to complete this quest",
		recurrence: 'daily',
		tokensReward: 300,
		charactersReward: "2nd Place",
	},
	{
		id: 51,
		name: "Perk Pride",
		description: "Include the name of one of your perks in your current name (case insensitive)",
		recurrence: 'weekly',
		tokensReward: 800,
		charactersReward: "🧩PerksRule",
	},
	{
		id: 52,
		name: "Role Call",
		description: "Include your role's name in your current name (case insensitive)",
		recurrence: 'weekly',
		tokensReward: 800,
		charactersReward: "👤RolesRule",
	},
	{
		id: 57,
		name: "Show Tokens",
		description: "Include the exact number of tokens you currently hold in your published name.",
		recurrence: "weekly",
		tokensReward: 1000,
		charactersReward: "exact count"
	},
	{
		id: 58,
		name: "Gold Spike",
		description: "Earn at least 10 tokens from a single mine attempt.",
		recurrence: "weekly",
		tokensReward: 500,
		charactersReward: "gold+"
	},
	{
		id: 60,
		name: "Speed Mine",
		description: "Execute 250 mining actions within a 10-minute span.",
		recurrence: "weekly",
		tokensReward: 650
	},
	{
		id: 61,
		name: "Mine Haul",
		description: "Earn at least 1,500 total tokens from mining this week.",
		recurrence: "weekly",
		tokensReward: 900,
		charactersReward: "mineshaft"
	},
	{
		id: 63,
		name: "Instant Squad",
		description: "Coordinate with five other players to mine together within a 5-second window.",
		recurrence: "weekly",
		tokensReward: 875,
	},
	{
		id: 64,
		name: "Ten-Minute Rush",
		description: "Collect at least 400 tokens total from only mines within a 10-minute window.",
		recurrence: "weekly",
		tokensReward: 1000,
		charactersReward: "diamonds"
	},
	{
		id: 65,
		name: "Coalition",
		description: "Help the server earn 3,500 total tokens from mining this week.",
		recurrence: "weekly",
		tokensReward: 1500
	},
	{
		id: 66,
		name: "Refill Raid",
		description: "Claim a single refill that grants at least 500 tokens.",
		recurrence: "weekly",
		tokensReward: 750,
		charactersReward: "big-refill"
	},
	{
		id: 69,
		name: "Mass Refill",
		description: "Claim a refill with five other players in the span of one minute.",
		recurrence: "weekly",
		tokensReward: 855,
		charactersReward: "5friends"
	},
	{
		id: 70,
		name: "Cold Server",
		description: "Ensure no player claims a refill for a continuous 16-hour period.",
		recurrence: "weekly",
		tokensReward: 1000,
		charactersReward: "16 quiet hours"
	},
	{
		id: 71,
		name: "Box Binge",
		description: "Open 25 mystery boxes during the week.",
		recurrence: "weekly",
		tokensReward: 500,
		charactersReward: "boxlover"
	},
	{
		id: 72,
		name: "Hyper Boxes",
		description: "Open 10 mystery boxes within a 3-minute window.",
		recurrence: "weekly",
		tokensReward: 800,
		charactersReward: "open(x10)"
	},
	{
		id: 73,
		name: "Namesake Box",
		description: "Open a mystery box while your published name contains that box's official name (case insensitive).",
		recurrence: "weekly",
		tokensReward: 1456,
	},
	{
		id: 74,
		name: "Rightmost",
		description: "Obtain the rightmost character of your current name from a mystery box.",
		recurrence: "weekly",
		tokensReward: 925,
		charactersReward: "→end"
	},
	{
		id: 76,
		name: "Buyout",
		description: "Purchase at least one of every available mystery box type.",
		recurrence: "weekly",
		tokensReward: 4000
	},
	{
		id: 77,
		name: "Triple Pull",
		description: "Open one mystery box and receive three characters from that single box.",
		recurrence: "weekly",
		tokensReward: 1000,
		charactersReward: "triple!"
	},
	{
		id: 78,
		name: "Find X",
		description: "Obtain the character \"x\" from any mystery box.",
		recurrence: "weekly",
		tokensReward: 650,
		charactersReward: "xxxxx"
	},
	{
		id: 79,
		name: "Sevens",
		description: "Receive the same character from a mystery box seven separate times this week.",
		recurrence: "weekly",
		tokensReward: 1100,
		charactersReward: "unlucky7"
	},
	{
		id: 80,
		name: "Priced Right",
		description: "Buy a mystery box while its token price is included in your current name.",
		recurrence: "weekly",
		tokensReward: 1234,
		charactersReward: "★ Gold Star"
	},
	{
		id: 81,
		name: "Crafting Marathon",
		description: "Craft using at least 15 different recipes during the week.",
		recurrence: "weekly",
		tokensReward: 815,
		charactersReward: "crafting table"
	},
	{
		id: 82,
		name: "Emoji Craft",
		description: "Craft three emoji characters this week.",
		recurrence: "weekly",
		tokensReward: 1280,
		charactersReward: "😯😃😶"
	},
	{
		id: 83,
		name: "Bulk Recipe",
		description: "Use a recipe that requires at least five input characters and returns a single character.",
		recurrence: "weekly",
		tokensReward: 1303
	},
	{
		id: 84,
		name: "Utility Master",
		description: "Craft characters using every available recipe utility character at least once.",
		recurrence: "weekly",
		tokensReward: 1200,
		charactersReward: "multi-tool"
	},
	{
		id: 85,
		name: "Tri-Forge",
		description: "Produce the same character using three different recipes.",
		recurrence: "weekly",
		tokensReward: 900,
		charactersReward: "three-way-forge"
	},
	{
		id: 86,
		name: "Input Remix",
		description: "Use the same input characters in three different recipes and get three distinct outputs.",
		recurrence: "weekly",
		tokensReward: 900,
		charactersReward: "↻↻↻⇋⇋⇋⤻⤻↹↹⚭⚭✂⤡⇔"
	},
	{
		id: 87,
		name: "Chaotic Trade",
		description: "Trade a single character and receive at least 20 characters in return.",
		recurrence: "weekly",
		tokensReward: 987,
		charactersReward: "scammed!!!"
	},
	{
		id: 88,
		name: "Wide Diplomat",
		description: "Have trades accepted by five different players this week.",
		recurrence: "weekly",
		tokensReward: 865,
		charactersReward: "trade5"
	},
	{
		id: 89,
		name: "Chain Five",
		description: "Accept five distinct trades from five different players.",
		recurrence: "weekly",
		tokensReward: 865,
		charactersReward: "popular5"
	},
	{
		id: 90,
		name: "Pity Pass",
		description: "Decline a trade that would have given you 20 or more characters than you offered.",
		recurrence: "weekly",
		tokensReward: 700,
		charactersReward: ":-,)"
	},
	{
		id: 91,
		name: "Quest Hoard",
		description: "Complete 20 different quests during the week.",
		recurrence: "weekly",
		tokensReward: 1000
	},
	{
		id: 92,
		name: "Quad Combo",
		description: "Complete four quests within the span of one minute.",
		recurrence: "weekly",
		tokensReward: 1111,
		charactersReward: "QUEST SYNC"
	},
	{
		id: 93,
		name: "Name Match",
		description: "Complete any quest while your current name contains that quest's exact name (case insensitive).",
		recurrence: "weekly",
		tokensReward: 1250,
		charactersReward: "name-tag"
	},
	{
		id: 94,
		name: "Quest Bounty",
		description: "Gain a total of 20 characters from quest rewards this week.",
		recurrence: "weekly",
		tokensReward: 850,
		charactersReward: "here's 14 more"
	},
	{
		id: 95,
		name: "Quest Riches",
		description: "Earn a total of 1,500 tokens from quest rewards during the week.",
		recurrence: "weekly",
		tokensReward: 950,
		charactersReward: "qqq1500"
	},
	{
		id: 96,
		name: "Synchronized",
		description: "Complete the same quest at the same moment as five other players within one minute.",
		recurrence: "weekly",
		tokensReward: 1200,
		charactersReward: "sync5"
	},
	{
		id: 98,
		name: "No Perk",
		description: "Avoid picking any perk for six consecutive days.",
		recurrence: "weekly",
		tokensReward: 765,
		charactersReward: "I am perk free"
	},
	{
		id: 99,
		name: "Perk Name",
		description: "Pick a perk while your current name contains that perk's exact name.",
		recurrence: "weekly",
		tokensReward: 1800,
		charactersReward: "😱 no way"
	},
	{
		id: 100,
		name: "Unique Perk",
		description: "Pick a perk that no other player on your server has selected.",
		recurrence: "weekly",
		tokensReward: 1000,
		charactersReward: "you are special :)"
	},
	{
		id: 102,
		name: "Fast Fortune",
		description: "Gain 2,000 total tokens by any means during the week.",
		recurrence: "weekly",
		tokensReward: 950,
		charactersReward: "A Fast 2k"
	},
	{
		id: 105,
		name: "Complete Set",
		description: "Have 100 unique characters in your inventory.",
		recurrence: "weekly",
		tokensReward: 1500
	},
	{
		id: 107,
		name: "Unmoved",
		description: "Keep your current name unchanged for 24 hours.",
		recurrence: "weekly",
		tokensReward: 600,
		charactersReward: "stability"
	},
	{
		id: 108,
		name: "Silent Server",
		description: "Ensure no player changes their name for an 8-hour continuous window.",
		recurrence: "weekly",
		tokensReward: 900,
		charactersReward: "aaaeeeiiiooouuu"
	},
] as const;
