export const quests = [
	{
		id: 1,
		name: "Experienced Craftsman",
		description: "Craft characters at least five times using at least three different recipes",
		tokensReward: 75,
	},
	{
		id: 2,
		name: "Diverse Name",
		description: "Have your currently published name contain at least 1 letter, 1 symbol, and 1 number",
		tokensReward: 350,
	},
	{
		id: 3,
		name: "Trade Diplomat",
		description: "Successfully have your trade accepted by a player",
		tokensReward: 100,
		charactersReward: "trade",
	},
	{
		id: 4,
		name: "Twinsies",
		description: "Coordinate with another player to have the same published name as them",
		tokensReward: 200,
		charactersReward: "x",
	},
	{
		id: 5,
		name: "Get Rich Quick",
		description: "Gain 200 tokens total through any means necessary",
		tokensReward: 350,
		charactersReward: "tokens",
	},
	{
		id: 6,
		name: "Echoed Name",
		description: "Change your current name into a repeated version of itself. For example, from \"Pom\" to \"PomPom\"",
		tokensReward: 100,
		charactersReward: "echo",
	},
	{
		id: 7,
		name: "Identity Theft",
		description: "Change your current name to exactly match another player’s current name. Keep it that way for two hours straight",
		tokensReward: 350,
	},
	{
		id: 8,
		name: "Fragile Name",
		description: "Make sure your current name does not change for 8 hours straight",
		tokensReward: 500,
	},
	{
		id: 9,
		name: "Hour of Silence",
		description: "Ensure that no player changes their name for an hour straight",
		tokensReward: 250,
		charactersReward: "shhh",
	},
	{
		id: 10,
		name: "Even Number Name",
		description: "Publish a name that uses one of the following characters: 02468",
		tokensReward: 246,
		charactersReward: "13579",
	},
	{
		id: 11,
		name: "Distinct Dozen",
		description: "Publish a name that contains 12 unique characters",
		tokensReward: 120,
		charactersReward: "twelve",
	},
	{
		id: 12,
		name: "High Yield",
		description: "Earn at least five tokens from a single mine",
		tokensReward: 75,
		charactersReward: "gold",
	},
	{
		id: 13,
		name: "One Hundred Swings",
		description: "Mine 100 times",
		tokensReward: 150,
		charactersReward: "mmm",
	},
	{
		id: 14,
		name: "Rapid Extraction",
		description: "Mine at least 20 times in the span of a minute",
		tokensReward: 220,
	},
	{
		id: 15,
		name: "Miner's Fortune",
		description: "Earn at least 100 tokens just from mining",
		tokensReward: 100,
		charactersReward: "ore",
	},
	{
		id: 16,
		name: "Lucky Mining Streak",
		description: "Earn at least three tokens from a single mine five times",
		tokensReward: 125,
		charactersReward: "nnn",
	},
	{
		id: 17,
		name: "Refill Jackpot",
		description: "Earn at least 100 tokens from a single refill",
		tokensReward: 100,
		charactersReward: "refill",
	},
	{
		id: 18,
		name: "Mine Together",
		description: "Mine at the same time as two other players in the span of one minute",
		tokensReward: 250,
		charactersReward: "friend",
	},
	{
		id: 19,
		name: "Mining Speedrun",
		description: "Earn at least 35 total tokens from mines in the span of 1 minute",
		tokensReward: 125,
		charactersReward: "cash",
	},
	{
		id: 20,
		name: "Collective Mining",
		description: "Contribute to a total of 1,000 tokens mined collectively by all players",
		tokensReward: 150,
		charactersReward: "team",
	},
	{
		id: 21,
		name: "Refill Frenzy",
		description: "Claim five refills",
		tokensReward: 150,
	},
	{
		id: 22,
		name: "Instant Refill",
		description: "Claim a refill immediately after it's cooldown expires",
		tokensReward: 150,
		charactersReward: "fast",
	},
	{
		id: 23,
		name: "Refill Together",
		description: "Claim a refil at the same time as two other players in the span of one minute",
		tokensReward: 200,
		charactersReward: "trio",
	},
	{
		id: 24,
		name: "Treasure Hunter",
		description: "Open five mystery boxes",
		tokensReward: 125,
		charactersReward: "box",
	},
	{
		id: 25,
		name: "Rapid Boxes",
		description: "Open three mystery boxes in the span of one minute",
		tokensReward: 150,
		charactersReward: "speed",
	},
	{
		id: 26,
		name: "Familiar Face",
		description: "Obtain a character from a mystery box that is already in your current name",
		tokensReward: 175,
		charactersReward: "deja",
	},
	{
		id: 27,
		name: "Mystery Box Splurge",
		description: "Spend a total of 750 tokens on mystery boxes",
		tokensReward: 250,
		charactersReward: "spender",
	},
	{
		id: 28,
		name: "Mystery Box Collector",
		description: "Buy at least three different mystery boxes",
		tokensReward: 100,
		charactersReward: "a1!",
	},
	{
		id: 29,
		name: "Big Spender",
		description: "Open the most expensive mystery box",
		tokensReward: 300,
		charactersReward: "rich",
	},
	{
		id: 30,
		name: "Bonus Loot",
		description: "Receive more than one character from a single mystery box",
		tokensReward: 222,
		charactersReward: "two",
	},
	{
		id: 31,
		name: "Expected Reward",
		description: "Receive the letter \"e\" from a mystery box",
		tokensReward: 80,
		charactersReward: "aiou",
	},
	{
		id: 32,
		name: "Three of a Kind",
		description: "Receive the same character from a mystery box three times",
		tokensReward: 123,
		charactersReward: "three",
	},
	{
		id: 33,
		name: "ALL IN",
		description: "Spend all the tokens you have on a mystery box",
		charactersReward: "I'm broke",
	},
	{
		id: 34,
		name: "Emoji Alchemist",
		description: "Use any recipe to craft at an emoji",
		tokensReward: 200,
		charactersReward: "😯",
	},
	{
		id: 35,
		name: "Many for One",
		description: "Craft a character using a recipe that requires at least three characters but produces only one character in return",
		tokensReward: 50,
		charactersReward: "↻⇋⤻↹⚭✂⤡⇔",
	},
	{
		id: 36,
		name: "Great Deal",
		description: "Trade a single character you own for at least three in return",
		tokensReward: 200,
		charactersReward: "deal",
	},
	{
		id: 37,
		name: "Crafty Crafter",
		description: "Craft characters three times using recipes that require a utility character",
		tokensReward: 200,
		charactersReward: "⇋Flip",
	},
	{
		id: 38,
		name: "Large Output",
		description: "Use a crafting recipe that produces at least two characters",
		tokensReward: 250,
		charactersReward: "✂Split",
	},
	{
		id: 39,
		name: "Dual Artisan",
		description: "Craft the same character using two different recipes",
		tokensReward: 225,
		charactersReward: "⚭Fuse",
	},
	{
		id: 40,
		name: "Recipe Remix",
		description: "Use the same input characters in two different recipes to produce different outputs",
		tokensReward: 300,
		charactersReward: "⇔Stretch",
	},
	{
		id: 41,
		name: "Scam",
		description: "Successfully trade only one of your characters to receive at least five characters in return",
		tokensReward: 200,
		charactersReward: "!@#$",
	},
	{
		id: 42,
		name: "Seal The Deal",
		description: "Accept a trade request",
		tokensReward: 100,
		charactersReward: "ok",
	},
	{
		id: 43,
		name: "Rejecting Profit",
		description: "Decline a trade request where you would have received at least 5 more characters than you were giving",
		tokensReward: 150,
		charactersReward: "compensation",
	},
	{
		id: 44,
		name: "Final Offer",
		description: "Have a trade request that you modified be accepted by the other player",
		tokensReward: 250,
		charactersReward: "modify",
	},
	{
		id: 45,
		name: "Quest Combo",
		description: "Complete two separate quests consecutively in the span of ten minutes",
		tokensReward: 150,
		charactersReward: "quick",
	},
	{
		id: 46,
		name: "Hoard Tokens",
		description: "Accumulate a total of 200 tokens without spending any",
		tokensReward: 200,
	},
	{
		id: 47,
		name: "The Richest",
		description: "Have the most tokens out of all players",
		tokensReward: 250,
		charactersReward: "🪙w3alτhy",
	},
	{
		id: 48,
		name: "Character Collector",
		description: "Have 35 unique characters in your inventory",
		tokensReward: 350,
		charactersReward: "=-+-=",
	},
	{
		id: 49,
		name: "You Snooze You Lose",
		description: "Be the first player to complete this quest",
		tokensReward: 500,
		charactersReward: "The Fastest",
	},
	{
		id: 50,
		name: "You Snooze You Win",
		description: "Be the second player to complete this quest",
		tokensReward: 350,
		charactersReward: "2nd Place",
	},
] as const;

